# Generated by Django 4.2.6 on 2024-04-03 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_deposit_proof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit_wallets',
            name='ticker_code',
        ),
    ]
