# Generated by Django 4.2.6 on 2024-04-04 00:54

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_deposit_wallets_ticker_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verification_document',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
