# Generated by Django 4.2.6 on 2024-04-04 01:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_profile_verification_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='verification_document',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Verification Document'),
        ),
    ]
