# Generated by Django 4.2.6 on 2024-04-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_profile_trading_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='copytrader',
            name='followers',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
