# Generated by Django 4.2.6 on 2024-04-08 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_trade_expert_trade_trade_lost_trade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='confirmed',
        ),
        migrations.AddField(
            model_name='deposit',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('declined', 'declined'), ('approved', 'approved')], default='pending', max_length=20),
        ),
    ]
