# Generated by Django 4.2.6 on 2024-06-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_remove_deposit_confirmed_deposit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='verification_document',
            field=models.FileField(blank=True, null=True, upload_to='documents'),
        ),
    ]
