# Generated by Django 4.2.6 on 2024-06-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_profile_verification_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit_wallets',
            name='ticker_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
