# Generated by Django 4.2.6 on 2024-08-23 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_deposit_wallets_ticker_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='document_type',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_document2',
            field=models.FileField(blank=True, null=True, upload_to='documents'),
        ),
    ]
